#!/bin/bash
# usage: ./temperatur system
# usage: ./temperatur innen

INPUT_DEVICE=`echo "$1" | awk '{print tolower($0)}'`

if [ "$INPUT_DEVICE" == "system" ];
then
	INPUT=$(awk "BEGIN {print $(/bin/cat /sys/class/thermal/thermal_zone0/temp)/1000}")
	echo $INPUT
	exit;
fi


if [[ "$INPUT_DEVICE" == "gpio7" ]] || [[ "$INPUT_DEVICE" == "innen" ]];
then
	GPIO=7
	INPUT=$(sudo /home/pi/lol_dht22/loldht $GPIO | grep "Temperature")
	HUM=$(echo $INPUT|cut -d " " -f3)
	TEMP=$(echo $INPUT|cut -d " " -f7)
	echo $TEMP
fi
