#!/bin/bash
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

INPUT_DEVICE=`echo "$1" | awk '{print tolower($0)}'`

if [[ "$INPUT_DEVICE" == "kinderzimmer" ]];
then
	export EQ3_MAC="00:1A:22:0B:A5:D2"
else
	export EQ3_MAC=$INPUT_DEVICE
fi


if [[ "$2" == "boost" ]];
then
	$3=1
fi

shift
eq3cli $@
